/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI
 * Method:    getByteArray
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_JNI_getByteArray
  (JNIEnv *, jobject);

/*
 * Class:     JNI
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_printHello
  (JNIEnv *, jobject);

/*
 * Class:     JNI
 * Method:    releaseByteArray
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_JNI_releaseByteArray
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
