/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class P5NewCryptData */

#ifndef _Included_P5NewCryptData
#define _Included_P5NewCryptData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     P5NewCryptData
 * Method:    P5_JavaDummyCall
 * Signature: ([BI[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_P5NewCryptData_P5_1JavaDummyCall
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     P5NewCryptData
 * Method:    testFunction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_P5NewCryptData_testFunction
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
