/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniExceptionTest */

#ifndef _Included_JniExceptionTest
#define _Included_JniExceptionTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniExceptionTest
 * Method:    exception
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniExceptionTest_exception
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
