/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestClass */

#ifndef _Included_TestClass
#define _Included_TestClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestClass
 * Method:    GetString
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_TestClass_GetString
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
