/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class P5Exception */

#ifndef _Included_P5Exception
#define _Included_P5Exception
#ifdef __cplusplus
extern "C" {
#endif
#undef P5Exception_serialVersionUID
#define P5Exception_serialVersionUID -3042686055658047285LL
#undef P5Exception_serialVersionUID
#define P5Exception_serialVersionUID -3387516993124229948LL
#undef P5Exception_serialVersionUID
#define P5Exception_serialVersionUID -7034897190745766939LL
/*
 * Class:     P5Exception
 * Method:    throwException
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_P5Exception_throwException
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
