/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SigTest */

#ifndef _Included_SigTest
#define _Included_SigTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SigTest
 * Method:    stringSig
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_SigTest_stringSig
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
